version: '3.8'

services:

  backend:
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cqlqpto8fa8c73bngk1g-a:5432/mypostgresql_ib4g
      SPRING_DATASOURCE_USERNAME: mypostgresql_ib4g_user
      SPRING_DATASOURCE_PASSWORD: oBUp4fewm6Uryl4QfvkCsQTRjlDyGj0y
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mypostgresql_ib4g_user
      POSTGRES_PASSWORD: oBUp4fewm6Uryl4QfvkCsQTRjlDyGj0y
      POSTGRES_DB: mypostgresql_ib4g
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: